name: Deploy to production environment

# Controls when the action will run
on:
  # Triggers the workflow on repository-dispatch event
  repository_dispatch:
    types: [production-deployment]

# This workflow is made up of one job that calls the reusable workflow in graasp-deploy
jobs:
  graasp-deploy-s3-workflow:
    # Replace with repository name
    name: Graasp auth
    # Replace 'main' with the hash of a commit, so it points to an specific version of the reusable workflow that is used
    # Reference reusable workflow file. Using the commit SHA is the safest for stability and security
    uses: graasp/graasp-deploy/.github/workflows/cdeployment-s3.yml@v1
    # Replace input build-folder if needed.
    with:
      build-folder: 'build'
      tag: ${{ github.event.client_payload.tag }}
    # Insert required secrets based on repository with the following format: ${{ secrets.SECRET_NAME }}
    secrets:
      ga-measurement-id: ${{ secrets.REACT_APP_GA_MEASUREMENT_ID_PROD }}
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
      aws-region: ${{ secrets.AWS_REGION_PROD }}
      aws-s3-bucket-name: ${{ secrets.AWS_S3_BUCKET_NAME_GRAASP_AUTH_PROD }}
      cloudfront-distribution-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_GRAASP_AUTH_PROD }}
      api-host: ${{ secrets.REACT_APP_API_HOST_PROD }}
      show-notifications: ${{ secrets.REACT_APP_SHOW_NOTIFICATIONS }}
      graasp-compose-host: ${{ secrets.REACT_APP_GRAASP_COMPOSE_HOST_PROD }}
      graasp-explorer-host: ${{ secrets.REACT_APP_GRAASP_EXPLORE_HOST_PROD }}
      domain: ${{ secrets.REACT_APP_DOMAIN_PROD }}
